apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneretail-test
  namespace: argocd
  labels:
    env: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: octopus
  project: default
  source:
    path: manifests/app/base
    repoURL: https://github.com/kratarget/octopus_oneretail_deploy.git
    targetRevision: test
  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
    syncOptions:
      - PruneLast=true