apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: octopus

resources:
- namespace.yaml
- registry-secret.yaml
- deploy.yaml
- service.yaml
images:
- name: oneretailhackaton.jfrog.io/virtual-docker/kratarget/octopus_oneretail_deploy
  newTag: "34"
