apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJvbmVyZXRhaWxoYWNrYXRvbi5qZnJvZy5pbyI6eyJ1c2VybmFtZSI6Inlhc2luLmtveXVuY3VAZXh0ZXJuYWwuZW5naWUuY29tIiwicGFzc3dvcmQiOiJjbVZtZEd0dU9qQXhPakUzTnpBek9EQTFNakU2VlRJNE5raFlkRVp6ZFVwQlpHdEdabXR0V0hOU00zcHpXWGxuIiwiYXV0aCI6ImVXRnphVzR1YTI5NWRXNWpkVUJsZUhSbGNtNWhiQzVsYm1kcFpTNWpiMjA2WTIxV2JXUkhkSFZQYWtGNFQycEZNMDU2UVhwUFJFRXhUV3BGTmxaVVNUUk9hMmhaWkVWYWVtUlZjRUphUjNSSFdtMTBkRmRJVGxOTk0zQjZWMWhzYmc9PSJ9fX0K
kind: Secret
metadata:
  name: oneretailhackaton
  namespace: octopus
type: kubernetes.io/dockerconfigjson