apiVersion: v1
kind: Service
metadata:
  labels:
    app: oneretail-app
  name: my-service
  namespace: octopus
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: oneretail-app