apiVersion: v1
kind: Service
metadata:
  labels:
    app: oneretail-app
  name: oneretail-app
  namespace: octopus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: oneretail-app