
name: Deploy upon dispatch
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-event]  # same as 'event_type' from Repo A

env:
  REGISTRY: oneretailhackaton.jfrog.io/virtual-docker
  IMAGE_NAME: oneretailhackaton.jfrog.io/virtual-docker/${{ github.repository }}:${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out Repo A
        uses: actions/checkout@v4

      - name: Check out Repo Source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SOURCE_REPO_SECRET }}
          repository: 'kratarget/oneretail-app'
          ref: 'master'
          path: 'app'
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: oneretailhackaton.jfrog.io/virtual-docker
          username: amine.zaine@external.engie.com
          password: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "./app"
          file: "./Dockerfile"
          push: true
          tags: ${{ env.IMAGE_NAME }}
